#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug 				# change this option for non-debug runs
#SBATCH -N 2					  # adjust the number of nodes per test (e.g. start with 1, 2, ...)
#SBATCH -t 00:30:00		  # adjust the amount of time as necessary
#SBATCH -J P2P
#SBATCH -o P2P.%j.stdout
#SBATCH -e P2P.%j.error

export MPICH_MAX_THREAD_SAFETY=MPI_THREAD_MULTIPLE
export OMP_NUM_THREADS=64

echo "P2P_Send_Multi_MPIs Starts"
srun -N 2 -n 128 ./P2P_Send_Multi_MPIs -B 0 -F 0 -N 1
srun -N 2 -n 128 ./P2P_Send_Multi_MPIs -B 0 -F 0 -N 2
srun -N 2 -n 128 ./P2P_Send_Multi_MPIs -B 0 -F 0 -N 4
srun -N 2 -n 128 ./P2P_Send_Multi_MPIs -B 0 -F 0 -N 8
srun -N 2 -n 128 ./P2P_Send_Multi_MPIs -B 0 -F 0 -N 16
srun -N 2 -n 128 ./P2P_Send_Multi_MPIs -B 0 -F 0 -N 32
#srun -N 2 -n 128 ./P2P_Send_Multi_MPIs -B 0 -F 0 -N 64
echo "P2P_Send_Multi_MPIs Ends \n"

echo "P2P_Send_Multi_OpenMP 2*64 Starts"
srun -N 2 -n 2 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 64 -N 1
srun -N 2 -n 2 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 64 -N 2
srun -N 2 -n 2 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 64 -N 4
srun -N 2 -n 2 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 64 -N 8
srun -N 2 -n 2 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 64 -N 16
srun -N 2 -n 2 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 64 -N 32
#srun -N 2 -n 2 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 64 -N 64
echo "P2P_Send_Multi_OpenMP 2*64 Ends \n"

echo "P2P_Send_Multi_OpenMP 4*32 Starts"
srun -N 2 -n 4 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 32 -N 1
srun -N 2 -n 4 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 32 -N 2
srun -N 2 -n 4 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 32 -N 4
srun -N 2 -n 4 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 32 -N 8
srun -N 2 -n 4 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 32 -N 16
srun -N 2 -n 4 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 32 -N 32
#srun -N 2 -n 4 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 32 -N 64
echo "P2P_Send_Multi_OpenMP 4*32 Ends \n"

echo "P2P_Send_Multi_OpenMP 8*16 Starts"
srun -N 2 -n 8 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 16 -N 1
srun -N 2 -n 8 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 16 -N 2
srun -N 2 -n 8 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 16 -N 4
srun -N 2 -n 8 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 16 -N 8
srun -N 2 -n 8 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 16 -N 16
srun -N 2 -n 8 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 16 -N 32
#srun -N 2 -n 8 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 16 -N 64
echo "P2P_Send_Multi_OpenMP 8*16 Ends \n"

echo "P2P_Send_Multi_OpenMP 16*8 Starts"
srun -N 2 -n 16 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 8 -N 1
srun -N 2 -n 16 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 8 -N 2
srun -N 2 -n 16 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 8 -N 4
srun -N 2 -n 16 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 8 -N 8
srun -N 2 -n 16 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 8 -N 16
srun -N 2 -n 16 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 8 -N 32
#srun -N 2 -n 16 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 8 -N 64
echo "P2P_Send_Multi_OpenMP 16*8 Ends \n"

echo "P2P_Send_Multi_OpenMP 32*4 Starts"
srun -N 2 -n 32 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 4 -N 1
srun -N 2 -n 32 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 4 -N 2
srun -N 2 -n 32 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 4 -N 4
srun -N 2 -n 32 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 4 -N 8
srun -N 2 -n 32 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 4 -N 16
srun -N 2 -n 32 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 4 -N 32
#srun -N 2 -n 32 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 4 -N 64
echo "P2P_Send_Multi_OpenMP 32*4 Ends \n"

echo "P2P_Send_Multi_OpenMP 64*2 Starts"
srun -N 2 -n 64 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 2 -N 1
srun -N 2 -n 64 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 2 -N 2
srun -N 2 -n 64 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 2 -N 4
srun -N 2 -n 64 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 2 -N 8
srun -N 2 -n 64 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 2 -N 16
srun -N 2 -n 64 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 2 -N 32
#srun -N 2 -n 64 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 2 -N 64
echo "P2P_Send_Multi_OpenMP 64*2 Ends \n"

echo "P2P_Send_Multi_OpenMP 128*1 Starts"
srun -N 2 -n 128 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 1 -N 1
srun -N 2 -n 128 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 1 -N 2
srun -N 2 -n 128 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 1 -N 4
srun -N 2 -n 128 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 1 -N 8
srun -N 2 -n 128 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 1 -N 16
srun -N 2 -n 128 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 1 -N 32
#srun -N 2 -n 128 ./P2P_Send_Multi_OpenMP -B 0 -F 0 -T 1 -N 64
echo "P2P_Send_Multi_OpenMP 128*1 Ends \n"

exit
