#!/bin/bash -l 
#SBATCH -C haswell
#SBATCH -p debug 
#SBATCH -N 2 
#SBATCH -t 00:30:00 
#SBATCH -J ScatterCross-haswell
#SBATCH -o ScatterCross-haswell.%j.stdout 
#SBATCH -e ScatterCross-haswell.%j.error 
export OMP_PROC_BIND=true 
export OMP_PLACES=threads 
export MPICH_MAX_THREAD_SAFETY=MPI_THREAD_MULTIPLE 
export OMP_NUM_THREADS=64 

echo "Scatter baseline, ranks/node:32, max msg size:32KB " 
srun -N 2 -n 64 -c 2 --cpu_bind=cores ./Scatter_MPI -B 0 -F 0 -N 1
srun -N 2 -n 64 -c 2 --cpu_bind=cores ./Scatter_MPI -B 0 -F 0 -N 2
srun -N 2 -n 64 -c 2 --cpu_bind=cores ./Scatter_MPI -B 0 -F 0 -N 4
srun -N 2 -n 64 -c 2 --cpu_bind=cores ./Scatter_MPI -B 0 -F 0 -N 8
srun -N 2 -n 64 -c 2 --cpu_bind=cores ./Scatter_MPI -B 0 -F 0 -N 16
srun -N 2 -n 64 -c 2 --cpu_bind=cores ./Scatter_MPI -B 0 -F 0 -N 32
echo " " 

echo "Scatter Hybrid, ranks/node:1 number of threads: 32, max msg size:32KB " 
srun -N 2 -n 2 -c 64 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 32 -N 1
srun -N 2 -n 2 -c 64 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 32 -N 2
srun -N 2 -n 2 -c 64 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 32 -N 4
srun -N 2 -n 2 -c 64 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 32 -N 8
srun -N 2 -n 2 -c 64 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 32 -N 16
srun -N 2 -n 2 -c 64 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 32 -N 32
echo " " 


echo "Scatter Hybrid, ranks/node:8 number of threads: 4, max msg size:32KB " 
srun -N 2 -n 16 -c 8 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 4 -N 1
srun -N 2 -n 16 -c 8 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 4 -N 2
srun -N 2 -n 16 -c 8 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 4 -N 4
srun -N 2 -n 16 -c 8 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 4 -N 8
srun -N 2 -n 16 -c 8 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 4 -N 16
srun -N 2 -n 16 -c 8 --cpu_bind=cores ./Scatter_OpenMP -B 0 -F 0 -T 4 -N 32
echo " " 


